version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build:
      context: .
    container_name: crypto_app
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./data:/app/data
      - ./plots:/app/plots
      - ./logs:/app/logs
    command: python main.py --start-date 2025-03-17 --end-date 2025-03-19 --coin-id bitcoin,ethereum,cardano --store
